### ISSUE TITLE
Issue with downloading free courses during sales period

### ISSUE THREAD

**Issue by akashnimare** [li-xinyang/OS_FrontendMaster-dl#16]
Is it possible to download the free courses available ie - 

![image](https://cloud.githubusercontent.com/assets/2263909/24583961/823bd750-1779-11e7-9493-d64196d2dda7.png)

I don't have a premium account. I'm trying to download the current free available courses 😺 

running on macOS - 
```sh
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 9, in downloader
    spider = Spider()
  File "/Users/akka/dev/OS_FrontendMaster-dl/extractor/spider.py", line 22, in __init__
    self.browser = webdriver.Chrome()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 415, in execute
    return self._request(command_info[0], url, body=data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 447, in _request
    resp = self._conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```
what I'm doing wrong?

**Comment by li-xinyang** [comment]
This tool is not tested again this situation because the free course is just temporary during sales period, however, the tool should work these courses.

Have you installed the Chrome web-driver?

**Comment by akashnimare** [comment]
Yes.
> `brew install chromedriver`

**Comment by li-xinyang** [comment]
Based on the SO http://stackoverflow.com/questions/27619258/httplib-badstatusline the suggestion is to upgrade web-driver. 

The error trace above indicates the issue is related with `selenium` and `httplib` not the tool itself.

**Comment by Nosenation** [comment]
Same issue here
<img width="871" alt="zrzut ekranu 2017-04-02 o 11 34 28" src="https://cloud.githubusercontent.com/assets/1431712/24586038/7d90b648-1798-11e7-863b-a631f5e3267f.png">

**Comment by akashnimare** [comment]
@Nosenation I solved it using - 
* Download the latest chromedrive which is 2.28 from here - https://sites.google.com/a/chromium.org/chromedriver/downloads
* Extract and move `chromedriver` file to `/usr/local/bin/chromedriver`
* Boom 🎉

**Comment by akashnimare** [comment]
Btw @li-xinyang could you please tell me the path of downloaded videos? I just ran the script and it's still running and retrieving videos but I don't see the downloaded videos 🤔

**Comment by Nosenation** [comment]
Didn't solve this for me.

**Comment by akashnimare** [comment]
What problem are facing now?

**Comment by Nosenation** [comment]
Same as on my screen.
Got newest chrome driver, newest python 2.7.13, all is in $PATH.

<img width="1249" alt="zrzut ekranu 2017-04-02 o 20 25 02" src="https://cloud.githubusercontent.com/assets/1431712/24589870/78c542b0-17e2-11e7-9236-bb207e7a849e.png">

**Comment by li-xinyang** [comment]
@Nosenation your issue is Chrome tab crash which is not the same issue as akashnimare post early.

I doubt that may cause by your local selenium installation. 

Alternatively, you can you Firefox to do the crawling. All you need to do is to change line below,

https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L22

to 

```
self.browser = webdriver.Firefox()
```

And of course, you need to download **Gecko Web-driver** to use it.

https://github.com/mozilla/geckodriver/releases
