### ISSUE TITLE
Cannot download after retrieving downloadable links

### ISSUE THREAD

**Issue by saiful619945** [li-xinyang/OS_FrontendMaster-dl#17]
After retrieving this happened. I install all the requirement.

```
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Users/saiful/Desktop/OS_FrontendMaster-dl-master/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/Users/saiful/Desktop/OS_FrontendMaster-dl-master/extractor/spider.py", line 174, in download_course
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/saiful/Desktop/OS_FrontendMaster-dl-master/extractor/helper.py", line 21, in download_file
    buff = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>
```

**Comment by li-xinyang** [comment]
Try to download another course if the same issue happen again.

**Comment by saiful619945** [comment]
Now it works. Thank you very much.
