### ISSUE TITLE
Script fails on MacOS 10.11.6

### ISSUE THREAD

**Issue by molk** [li-xinyang/OS_FrontendMaster-dl#18]
$ python frontendmasters-dl.py
Course ID: complete-intro-react
Username: xxx
Password: xxx
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 9, in downloader
    spider = Spider()
  File "/Users/molk/OS_FrontendMaster-dl/extractor/spider.py", line 22, in __init__
    self.browser = webdriver.Chrome()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 92, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 179, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 415, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 447, in _request
    resp = self._conn.getresponse()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

**Comment by li-xinyang** [comment]
https://code.google.com/archive/p/httplib2/issues/250

My suggestion is to change your network connection environment.

**Comment by molk** [comment]
I have no clue what you're suggesting here. httplib2? Do you have any more information for me?

**Comment by diegodesouza** [comment]
@molk I got a similar error as above, running Mac OS 10.12.4
this was after it was as if as it were downloading the videos, then at the end the error occurs.
```
...
Retriving: data-structures-algorithms/Hash_Tables/Hash_Tables
Video URL: blob:https://frontendmasters.com/4f95b979-1fff-414c-8f93-494a6787f7a2
Retriving: data-structures-algorithms/Hash_Tables/Pseudocoding_a_Hashing_Function
Video URL: blob:https://frontendmasters.com/9c5b810b-5081-4a6f-b7fa-58e484b9bf60
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Users/Documents/Code/OS_FrontendMaster-dl/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/Users/Documents/Code/OS_FrontendMaster-dl/extractor/spider.py", line 174, in download_course
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/Documents/Code/OS_FrontendMaster-dl/extractor/helper.py", line 21, in download_file
    buff = urlopen(url)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>```

**Comment by cabaret** [comment]
I'm getting the same error. Any ideas?

**Comment by diegodesouza** [comment]
I keep getting a similar error. I'm not sure what you mean to change the network connection environment.

**Comment by sepiropht** [comment]
Same for me

**Comment by elderbas** [comment]
I'm gonna guess that when you ran `pip install -r requirements.txt`, you had permission  issues, and you didn't end up installing the necessary Python library packages. This worked for me after I got your same errors.

```
# if you don't have virtualenv installed
pip install virtualenv

virtualenv my_project
source my_project/bin/activate
pip install -r requirements.txt
python frontendmasters-dl.py
```

**Comment by arvi** [comment]
@elderbas Thanks! It worked for me. :) Now I can study while on commute and have no internet. Yes!

**Comment by matthewepler** [comment]
Works! For anyone seaching for this solution, the errors I encounted before using this solution were:

`OSError: [Errno 1] Operation not permitted: '/tmp/pip-2zUzxH-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

and 

`OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/selenium'`
