### ISSUE TITLE
Downloading Not Possible Anymore

### ISSUE THREAD

**Issue by tonimain** [li-xinyang/OS_FrontendMaster-dl#24]
For a couple of days i get this strange error:

```
File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

But don't know how to solve this problem.

**Comment by li-xinyang** [comment]
I do not have a subscription to test it out. 

I think it might still work if the script can pass the user info (such as cookies or token) to the API.

**Comment by FlorinSenoner** [comment]
a quick and rather dirty fix would be something like this (in the `download_file` function):
`if not os.path.isfile(path) or os.path.getsize(path) == 0:
        browser.get(url)
        temporaryURL = browser.current_url
        browser.back()
        buff = urlopen(temporaryURL)
        print("Downloading: %s" % (path))`

**Comment by tonimain** [comment]
Will test it out my friends. Thanks for feedback so far

**Comment by tonimain** [comment]
than it says browser is not defined, here is the complete traceback from the actual error:
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Users/tonihaupt/Desktop/Frontendmasters/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/Users/tonihaupt/Desktop/Frontendmasters/extractor/spider.py", line 177, in download_course
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/tonihaupt/Desktop/Frontendmasters/extractor/helper.py", line 21, in download_file
    buff = urlopen(url)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by FlorinSenoner** [comment]
that's probably because I'm still using an earlier version. try self.browser instead of browser

**Comment by tonimain** [comment]
Now it says global name self is not defined rofl.

**Comment by tonimain** [comment]
dont know why it stopped working immediately. I also did reinstall python via brew but no results.

**Comment by tonimain** [comment]
defined the self inside the function param, testing out if this will work

**Comment by tonimain** [comment]
Not working. Modified the function to invoke the self but it is failing again.
@li-xinyang when i send you my credentials would you be able to debug the problem.
I'm running the script on osx latest with python install via brew.

**Comment by li-xinyang** [comment]
@tonimain I am kinda busy these days. I might be able to take a look during the coming weekend.

**Comment by tonimain** [comment]
okay thanks for your efforts

**Comment by FlorinSenoner** [comment]
did you pass the argument `self` to the function `download_file` -> `download_file(url, path, self)`

**Comment by tonimain** [comment]
Yep but also didn't work.

**Comment by FlorinSenoner** [comment]
did you update the function in the spider.py and helper.py file?

**Comment by tonimain** [comment]
Not really what should I do to update correctly?

**Comment by FlorinSenoner** [comment]
you also have to pass the self argument :) -> `download_file(subsection['downloadable_url'], file_path, self)`

**Comment by tonimain** [comment]
Thanks for your help so far.are there other parts where I have to change code?

**Comment by FlorinSenoner** [comment]
I did not test the code but it should work like this. do you still get an error?

**Comment by FlorinSenoner** [comment]
ah stupid mistake on my part, you have to include the download_file function in the spyder.py file (class Spyder)

**Comment by philgetz** [comment]
Having the same problem, updated the function on both spider.py and helper.py getting @tonimain 's same errors

**Comment by tonimain** [comment]
Now i get some awesome new errors 📦 
```
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: no such session
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.4 x86_64)
```

**Comment by callerc1** [comment]
@tonimain Your chrome webdriver instance has closed already try moving `self.browser.close` (https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L42) after the `self.download_course` method

**Comment by tonimain** [comment]
worked like charm my friend
thanks for help

**Comment by jileeshs** [comment]
@tonimain Could you please post the spider.py and helper.py worked for you.
Thanks

**Comment by jileeshs** [comment]
I am getting the following errors: 
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by MichalPaszowski** [comment]
After all modifications mentioned earlier, I don't get any errors any more. Script reports success and creates directory with course name but nothing is saved.

**Comment by shadrech** [comment]
For me it downloads one file then emits this error:
`Traceback (most recent call last):
  File "./frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Volumes/SECONDARY HDD/Videos/frontendmasters/OS_FrontendMaster-dl/extractor/spider.py", line 43, in download
    self.download_course(course_downloadbale)
  File "/Volumes/SECONDARY HDD/Videos/frontendmasters/OS_FrontendMaster-dl/extractor/spider.py", line 176, in download_course
    download_file(subsection['downloadable_url'], file_path)
  File "/Volumes/SECONDARY HDD/Videos/frontendmasters/OS_FrontendMaster-dl/extractor/helper.py", line 21, in download_file
    buff = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized`

**Comment by jileeshs** [comment]
Hi All, it is working!!! MAke all the above mentioned changes, including the one mentioned by @callerc1. Then remove the directory with the course name from your Downloads directory before retrying. Worked for me.

**Comment by shadrech** [comment]
@jileeshs Would you mind posting your helper.py and spider.py files?

**Comment by li-xinyang** [comment]
Yes, a PR is most welcomed. ❤️

**Comment by philgetz** [comment]
Ok everyone I got it working, and I don't see a PR so I will do one in a bit. I am testing it with other courses making sure it works fine should not take more than an hour.

**Comment by philgetz** [comment]
Ok submitted the [PR](https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/25) check out the changes there.

**Comment by hcheruku** [comment]
Hi guys;

I have the same problem. I tried on Windows, Linux, and OS X - still the same

So, I did a work around.
After retrieving the URLs, I just collected them to a .txt file.
I then supplied that .txt file to a file download manager.
I know it's not a clean way, but I was able to get the files downloaded

here's the 2 lines I added:
                    log = open("video_urls.txt", "a")
                    print(url_str, file = log)

I added the above two lines to: _get_downloadable_links function of a spider.py file
after line 141. i.e: print("Video URL: {0}".format(url_str))

Cheers!

**Comment by hcheruku** [comment]
oh! 
if you guys are following my work around:
don't forget to create .txt file inside the same folder

Happy Downloading!

**Comment by philgetz** [comment]
Also, for anyone interested, there is an API endpoint that displays all the urls for the videos which can be accessed if one is logged in. 

For the latest react course this is the api:
https://api.frontendmasters.com/v1/kabuki/courses/react

The endpoint returns a JSON object. The video urls are in 'lessondata' in the property 'sourcebase'. 
To get to the video add  '?r=720&f=webm' to the 'sourcebase' url.

For example:
https://api.frontendmasters.com/v1/kabuki/video/bt8kqk74co?r=720&f=webm

You can also change the parameters '?r=720&f=webm' to mp4 and higher resolution such as 1080

For Example:
https://api.frontendmasters.com/v1/kabuki/video/bt8kqk74co?r=1080&f=mp4

I am not a python expert but I am sure this would be a faster way to get all the links without having to iterate trough the sites. Get the links and add the extension than just download from a txt file using @hcheruku's method.

**Comment by hcheruku** [comment]
@philgetz 
Your fix works for me.
The main problem was that buff = urlopen(url), instead of buff = urlopen(temporaryURL)

Thank you.

**Comment by li-xinyang** [comment]
@philgetz Yes, using API should be MUCH faster then scrapping the site using Selenium (It seems taking forever). Of course, we can convert the tool into other languages (your preference) if necessary.

**Comment by hcheruku** [comment]
@li-xinyang 
I will try to write/start Python or Haskell this Sunday.

@philgetz 
Extracted the downloadable links using API. Files download in progress ;-)

The other work around I talked about was like a quick thing so I can learn the downloaded course on one side, and on the other hand the links will be saved to text while I finish my course.
hahaha

Cheers!

**Comment by li-xinyang** [comment]
I am cool with that currently I am busy with other things and do not have a subscription to test the script. You can create a new repo and I will provide redirection to your repo. Alternatively, I can give you the collaborator access to this repo.

**Comment by hcheruku** [comment]
@li-xinyang and all
I have a working python script to extract the links for all the courses using API.
Let me know if anyone just wants links to any course(s) or the script.
I would be happy to share the script but there's few things that needs to be done manually to make it working. But super fast though :-)

I am now in the process of:
1. automating another small functionality
2. adding downloading functionality in the same file or maybe a separate script
3. and, porting it to Haskell (just coz. I like Haskell)

Cheers!

**Comment by mal-hunter** [comment]
@hcheruku 
Haskell is good. Lemme know if you already started. I wanna help.

I already have a working python script to download the files.
Lemme know if anyone wants any course. 
I will share the script once I automate all the things. There's some parts where I am manually doing some tasks for the script to work. But it works really fast.
Once I find some time this month - I'll try to automate everything and share the script.

Cheers!

**Comment by mal-hunter** [comment]
@philgetz 
Yes, you are correct. I grabbed the links the similar way.

**Comment by li-xinyang** [comment]
The script has been updated. Please try the lastest version. Thank you.

**Comment by AshiqCSEWorld** [comment]
@philgetz  how can I get all the links from sourcebase property?
