### ISSUE TITLE
Updates related to new design

### ISSUE THREAD

**Issue by vvscode** [li-xinyang/OS_FrontendMaster-dl#27]
Since applying new design to the website tool doesn't work any more

```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 11, in downloader
    spider.login(id, password)
  File "/Users/vvs/repo/OS_FrontendMaster-dl/extractor/spider.py", line 28, in login
    username_field = self.browser.find_element_by_id('rcp_user_login')
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 791, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"id","selector":"rcp_user_login"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.32.498537 (cb2f855cbc7b82e20387eaf9a43f6b99b6105061),platform=Mac OS X 10.12.6 x86_64)
```

**Comment by li-xinyang** [comment]
Yes, I'm aware of the updating the new design but I am no longer subscribe their service. Please open a PR if you can fix the issue. Thanks.

**Comment by vvscode** [comment]
@li-xinyang 

Here it is https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/28

Could you help me with the line https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/28/files#diff-4a93111ab82a12a0e66e19a02dd8d317R82 ? There should be prescending sibling h3 text. I'm not familiar with the API 

Markup is next:
!(Section title)[https://www.dropbox.com/s/383ps5uf9p399rb/Screenshot%202017-09-10%2016.53.31.png?dl=1)

**Comment by li-xinyang** [comment]
Thank you, @vvscode for the PR. I cannot do it right now but I will try to complete somewhere next week.

Thanks again.

**Comment by vvscode** [comment]
@li-xinyang  mail me if you some help. Thx a lot

**Comment by li-xinyang** [comment]
The problem I have is I do not have a subscription, hence I could not test it. However, I think I can suggest you the right API(s) to look at later.

**Comment by marcinkrzeminski** [comment]
They are giving away some free courses at the moment so you could just get an account and try it out on the free courses that are available.

**Comment by vvscode** [comment]
@marcinkrzeminski  maybe you can help with my question?

https://github.com/li-xinyang/OS_FrontendMaster-dl/issues/27#issuecomment-328344206

It works for current design but filenames might be better

**Comment by marcinkrzeminski** [comment]
Hi,

not a python dev but I did some research and maybe this might work

```
course_section['title'] = item.find('..').find('h3', {'class', 'lessongroup'}).getText()
```

It looks like you just go up using find('..') as much as you want, kinda like relative paths. 

This is the SO post I have found: https://stackoverflow.com/questions/18079765/how-to-find-parent-elements-by-python-webdriver

Unfortunately I couldn't test because I'm getting an error on both repos when download is about to start

```
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Users/marcin/Desktop/OS_FrontendMaster-dl/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/Users/marcin/Desktop/OS_FrontendMaster-dl/extractor/spider.py", line 177, in download_course
    download_file(subsection['downloadable_url'], file_path, self)
  File "/Users/marcin/Desktop/OS_FrontendMaster-dl/extractor/helper.py", line 24, in download_file
    buff = urlopen(temporaryURL)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>
```

**Comment by vvscode** [comment]
@marcinkrzeminski  did you try on latest master?

**Comment by marcinkrzeminski** [comment]
I see, so when you're on the item level you're inside a section, is that correct? Then you would need to go one level up find('..') to be on section level and get the preceding sibling. 

Not sure if the syntax is correct, I can't test it as stated above

```
//  try this
item.find('..').find('/preceding-sibling::h3').getText() 

// or this
item.find('..').find('preceding-sibling::h3').getText() 
```

if that won't work I'm out of ideas :(

**Comment by marcinkrzeminski** [comment]
Hi again @vvscode 

I had some time to take a look at this a bit deeper and I have found a solution. Sent a pull request already including your changes regarding new design. If you wish to take a closer look please follow this link: https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/29/commits/123c3183551518c84aea9e0e49d8500e03a85eaf

Hope you don't mind I used a lot of your changes.

Tested on MacOS Sierra.

Have a great weekend everyone ;).

**Comment by li-xinyang** [comment]
Thanks, @vvscode and @marcinkrzeminski. The PR has been merged. Close the issue for now.
