### ISSUE TITLE
Error urllib2.URLError: <urlopen error unknown url type: blob>

### ISSUE THREAD

**Issue by avary** [li-xinyang/OS_FrontendMaster-dl#36]
Hello, I'm trying to run this script on ArchLinux with python 2.7 after scanning the link, when trying to download the video I got this error.

```
Video URL: blob:https://frontendmasters.com/949e7c5e-ee32-496f-b81f-3631291cc1e1
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/home/avar/githubz/OS_FrontendMaster-dl/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/home/avar/githubz/OS_FrontendMaster-dl/extractor/spider.py", line 181, in download_course
    download_file(subsection['downloadable_url'], file_path, self)
  File "/home/avar/githubz/OS_FrontendMaster-dl/extractor/helper.py", line 24, in download_file
    buff = urlopen(temporaryURL)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 452, in _open
    'unknown_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1266, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: < urlopen error unknown url type: blob >
```

**Comment by li-xinyang** [comment]
Apparently there something wrong in line `24` in the `helper.py` file.

```
File "/home/avar/githubz/OS_FrontendMaster-dl/extractor/helper.py", line 24, in download_file
buff = urlopen(temporaryURL)
```

You can start your debugging process there.

**Comment by silo** [comment]
Try install this: pip install --user fonttools
Solved the same issue you have for me

**Comment by silo** [comment]
And to easier install chromedriver on macOS . Run brew install chromedriver

**Comment by li-xinyang** [comment]
Thanks, @silo for providing the fix. Yeah, `brew` is a nice to have toolkit. Please reopen the issue if this does not fix your issue.

**Comment by denvercoder** [comment]
Same issue here. I tried the fonttools install and I tried installing chromedriver with homebrew still didn't work.
