### ISSUE TITLE
TimeoutException when downloading video

### ISSUE THREAD

**Issue by manuelteixeira** [li-xinyang/OS_FrontendMaster-dl#50]
Is this error happening to somebody else?
I tried with the new --video-per-video flag, but i get the same error.
Thanks.

```
Downloading: Introduction_to_State_Management
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 21, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.download(course)
  File "/Users/manuelteixeira/Downloads/OS_FrontendMaster-dl-master/extractor/spider.py", line 45, in download
    self.download_course(course_downloadbale)
  File "/Users/manuelteixeira/Downloads/OS_FrontendMaster-dl-master/extractor/spider.py", line 181, in download_course
    download_file(subsection['downloadable_url'], file_path, self)
  File "/Users/manuelteixeira/Downloads/OS_FrontendMaster-dl-master/extractor/helper.py", line 21, in download_file
    self.browser.get(url)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in get
    self.execute(Command.GET, {'url': url})
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

**Comment by diegodesouza** [comment]
I keep getting the same

**Comment by vvscode** [comment]
I've just downloaded the course - everything is fine

**Comment by KrzysztofKarol** [comment]
I debugged it and it hangs out for me at line
https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/4064f90e766668b34bd8a1b27f09ee023b552546/extractor/helper.py#L24

So I removed that
```javascript
self.browser.get(url)
temporaryURL = self.browser.current_url
self.browser.back()
```

and works like a charm.

BUT it was added as a fix by @philgetz in https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/25
Deeper investigation needed here.

**Comment by KrzysztofKarol** [comment]
Sorry I mistakenly added this issue as resolved by PR.
This: https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/56 resolves it but I must go deep with details in https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/25
