### ISSUE TITLE
ElementNotVisibleException: Message: element not visible

### ISSUE THREAD

**Issue by glen03xs** [li-xinyang/OS_FrontendMaster-dl#53]
I was able to download 2 courses then I encounter this error. I can download some videos but most of the time I have this error.

**Comment by li-xinyang** [comment]
I guess it might be caused by request timeout issue we discussed earlier in other issues. Do you have any error trace on the console you can post here?

**Comment by KrzysztofKarol** [comment]
This is caused by **429: You have reached maximum request limit.**
Video is not loaded so there is no quality button and no link to download it

<img width="529" alt="screen shot 2017-12-15 at 09 05 53" src="https://user-images.githubusercontent.com/12470911/34032619-48acba86-e177-11e7-92e5-0713fdb0f693.png">


```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/username/Projects/OS_FrontendMaster-dl/extractor/spider.py", line 45, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/username/Projects/OS_FrontendMaster-dl/extractor/spider.py", line 157, in _get_downloadable_links
    resolution_button.click()
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/Users/username/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.1 x86_64)
```

**Comment by glen03xs** [comment]
I apoligize li-xinyang I wasn't able to provide information. I have the same error as KrzysztofKarol posted.

**Comment by li-xinyang** [comment]
@glen03xs  no worries, I think the temp solution is to decrease crawler rate to avoid too many request in a limit amount of time.

**Comment by diegodesouza** [comment]
@li-xinyang can you point us to where this is in the code so that I could try it out? I tried increasing the wait time in `spider.py` not sure if that's what you meant. Though, I didn't get the results I expected. meaning i get the same `Error` mentioned above

**Comment by li-xinyang** [comment]
I think a throttle can be added to this function, https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L132. 

However, I already see there is a `sleep(8)` in line https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L160.

Can you try to increase the sleep time?

**Comment by KrzysztofKarol** [comment]
Hi I'm just preparing PR with auto-resume option and sleep for 15 minutes in case of "429: You have reached maximum request limit" error.
Already tested it and will be shipped in 10 minutes.

**Comment by li-xinyang** [comment]
@KrzysztofKarol Thanks for your contribution. I will review and merge the PR tomorrow morning. I think this tool can be improved a lot if we can find an alternative way to get the video source from their CDN.
