### ISSUE TITLE
It can't download the specific course

### ISSUE THREAD

**Issue by parelhutahaean** [li-xinyang/OS_FrontendMaster-dl#54]
I have followed all the instructions, yet I couldn't do it successfully. Instead there is error message:

Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)

  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.login(id, password)
  File "/home/pamanhu/OS_FrontendMaster-dl/extractor/spider.py", line 37, in login
    self.browser.get(URL_LOG_IN)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 323, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{
"frameId":"15980.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.9.248304,platform=Linux 4.10.0-42-generic x86_64)

Btw I'm using Ubuntu. What should I do?

**Comment by li-xinyang** [comment]
Google this error?

```
selenium.common.exceptions.WebDriverException: Message: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{
"frameId":"15980.1","isDefault":true},"id":1,"name":"","origin":"://"}
```

**Comment by li-xinyang** [comment]
> It can't download the specific course

**Comment by parelhutahaean** [comment]
Sorry for the confusion of my words. It didn't work for all the course because it caused an error. When I entered the command, then a browser window popped up with a notification that said "You are using unsupported command-line flag: --ignore-certificate-errors. Stability and security will suffer."

Then in the console the error message is like which I posted before. I don't understand python error message and webdriver. I'm just using the pip to download frontendmasters videos. I'm doing my best to understand the problem.

**Comment by li-xinyang** [comment]
Are you using the latest version? Can you try the headless mode?

**Comment by vvscode** [comment]
@parelhutahaean  the same question - which course can't you download?

**Comment by dance2die** [comment]
I had a similar problem on Windows.
It only happened when I tried to watch videos on FEM site while downloading videos.
Visiting FEM required me to log on so when I did, the download failed.

So the workaround is, don't log onto FEM while download is in progress.

**Comment by li-xinyang** [comment]
I do not think this is a bug in the script, it might have something to do with their site mechanism. Closing issue. 

Once again, thank you @vvscode for all your contribution, I added you into collaborators so you can push the code and approve PR to master.

**Comment by denvercoder** [comment]
I'm having a similar issue, I can't download the course with the course id:
full-stack-v2

but I was able to download 

full-stack

just fine.

It looks to me like maybe the structure of the URLS has changed and its confusing the script. It seems like the older courses download better than the newer ones.

Video URL: blob:https://frontendmasters.com/ee833872-c072-41ee-9275-8d1a307809c3
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 56, in download
    self.download_course(course_downloadbale)
  File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 219, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/Users/dev/OS_FrontendMaster-dl/extractor/spider.py", line 230, in download_video
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/dev/OS_FrontendMaster-dl/extractor/helper.py", line 52, in download_file
    buff = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>
