### ISSUE TITLE
UnboundLocalError: local variable 'course_path' referenced before assignment

### ISSUE THREAD

**Issue by davidhenley** [li-xinyang/OS_FrontendMaster-dl#57]
```
>>> Login with your credential
>>> Downloading course: react
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Users/david/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/david/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/david/Downloads/OS_FrontendMaster-dl-master/extractor/spider.py", line 52, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/david/Downloads/OS_FrontendMaster-dl-master/extractor/spider.py", line 155, in _get_downloadable_links
    i1, i2, subsection, section_title, course_path
UnboundLocalError: local variable 'course_path' referenced before assignment
```

Latest version

**Comment by benjamintanweihao** [comment]
I'm getting this too. A little digging reveals that during extraction the `download_url` for each `course` is `None`.

**Comment by davidhenley** [comment]
@benjamintanweihao I ended up scrapping this and just using their API to download:

https://api.frontendmasters.com/v1/kabuki/courses/react

You can find the url for each video, then add on ?r=720&f=mp4 and refresh a few times and hit download.

**Comment by li-xinyang** [comment]
yeah agree, API is a great way to get the URL for each video.

**Comment by aykutyunus2** [comment]
or just use https://chrome.google.com/webstore/detail/flash-video-downloader/aiimdkdngfcipjohbjenkahhlhccpdbc/reviews for each video.. Script would be better anyway.. Just he does not reply.

**Comment by vvscode** [comment]
@aykutyunus2  @benjamintanweihao @davidhenley  

use `--video-per-video` flag as temporary workaround

**Comment by vvscode** [comment]
https://github.com/li-xinyang/OS_FrontendMaster-dl/pull/59

**Comment by li-xinyang** [comment]
Thank you @vvscode for the PR. Happy new year 🎉
