### ISSUE TITLE
UnboundLocalError in Spider 

### ISSUE THREAD

**Issue by daohassane** [li-xinyang/OS_FrontendMaster-dl#58]
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/martianscamp/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 52, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/martianscamp/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 155, in _get_downloadable_links
    i1, i2, subsection, section_title, course_path
UnboundLocalError: local variable 'course_path' referenced before assignment

**Comment by li-xinyang** [comment]
```
