### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by RichMatthews** [li-xinyang/OS_FrontendMaster-dl#62]
I cloned the repo, cd'd inside. ran the command 
```
frontendmasters-dl.py --id BLANK --password BLANK. --course https://frontendmasters.com/courses/react-state/ --mute-audio --high-resolution 
```
then got this error:
```
File "frontendmasters-dl.py", line 1, in <module>
    import click
ImportError: No module named click
```

**Comment by vvscode** [comment]
@RichMatthews  you need install packages

```bash
pip install -r requirements.txt
```
inside the directory

**Comment by RichMatthews** [comment]
@vvscode I get an error when I run that:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
```

**Comment by RichMatthews** [comment]
@vvscode ok I have fixed that, now getting a chromedriver error. how do I put it into my python path?

**Comment by vvscode** [comment]
I have installed chrome driver in my system

**Comment by vvscode** [comment]
https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by RichMatthews** [comment]
@vvscode ok I have managed to do that now and now my screen out put looks like this after I run the main command:

```
>>> Login with your credential
>>> Downloading course: https://frontendmasters.com/courses/react-state/
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/rm/workspace/OS_FrontendMaster-dl/extractor/spider.py", line 49, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "/Users/rm/workspace/OS_FrontendMaster-dl/extractor/spider.py", line 75, in _get_detailed_course_list
    sections_items = sections.find_all(
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by rdrunner74** [comment]
You don't need the full URL for the course. just --course react-state
That should solve your issue.

**Comment by lostdesign** [comment]
```
tbMBP:OS_FrontendMaster-dl user$ python frontendmasters-dl.py 
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 1, in <module>
    import click
ImportError: No module named click

tbMBP:OS_FrontendMaster-dl user$ pip install click
Requirement already satisfied: click in /usr/local/lib/python2.7/site-packages
```

**Comment by denvercoder** [comment]
I have the same issue as lostDesign above.
