### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by vvscode** [li-xinyang/OS_FrontendMaster-dl#67]
```python
Retrieving: visual-studio-code/Debugging/Debugging_Chrome_with_VS_Code
Video URL: http://placehold.it/500x500
Downloading: Debugging_Chrome_with_VS_Code
Downloading: ./Download/visual-studio-code/4-3-Debugging-Debugging_Chrome_with_VS_Code.it/500x500
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/vvs/repo/OS_FrontendMaster-dl/extractor/spider.py", line 52, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/vvs/repo/OS_FrontendMaster-dl/extractor/spider.py", line 188, in _get_downloadable_links
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/Users/vvs/repo/OS_FrontendMaster-dl/extractor/spider.py", line 230, in download_video
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/vvs/repo/OS_FrontendMaster-dl/extractor/helper.py", line 55, in download_file
    with open(path, 'wb') as local_file:
IOError: [Errno 2] No such file or directory: u'./Download/visual-studio-code/4-3-Debugging-Debugging_Chrome_with_VS_Code.it/500x500'
```

**Comment by vvscode** [comment]
for my case, I fixed it with patching `helper.py` with try...except in `download_file()`

```python
    if not is_file_downloaded(path):
        buff = urlopen(url)
        print("Downloading: %s" % (path))
        try:
            with open(path, 'wb') as local_file:
                local_file.write(buff.read())
        except Exception as inst:
            print(inst)
```

**Comment by li-xinyang** [comment]
yeah, that was a quick fix to prevent the script from crashing long time ago. I believe your `try-except` should work and solve this issue.

**Comment by vvscode** [comment]
@li-xinyang  should I create the PR?

**Comment by li-xinyang** [comment]
yes, please create a PR to fix this.

**Comment by vvscode** [comment]
#68

**Comment by li-xinyang** [comment]
Merged, thanks :)
