### ISSUE TITLE
Unable to resume downloading the course

### ISSUE THREAD

**Issue by manishbisht** [li-xinyang/OS_FrontendMaster-dl#70]
Steps to reproduce:
1. Start downloading any course.
2. Stop the download after at least one video is downloaded.
3. Now start downloading the same course.
4. Displays the following error.
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/home/manish/Desktop/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/manish/Desktop/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/manish/Desktop/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/manish/Desktop/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/home/manish/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 56, in download
    self.download_course(course_downloadbale)
  File "/home/manish/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 219, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/home/manish/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 227, in download_video
    i1, i2, subsection, section_title, course_path
  File "/home/manish/Downloads/OS_FrontendMaster-dl/extractor/helper.py", line 16, in get_local_file_path
    extension = get_file_path_from_url(subsection['downloadable_url'])
  File "/home/manish/Downloads/OS_FrontendMaster-dl/extractor/helper.py", line 43, in get_file_path_from_url
    return url.split("?")[0].split(".")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by lostdesign** [comment]
Same issue as #63 i am guessing because there is already the a file with the same name. Trying now if thats the case.

**Comment by manishbisht** [comment]
Nope. I don't think this is the issue. Because I have checked even after deleting the files that are not downloaded.

**Comment by li-xinyang** [comment]
If I did not remember incorrectly, there is a file used to note down which file(s) is downloaded.

**Comment by aswathm78** [comment]
I checked the folder . No such files are available.

**Comment by vahidm-sp** [comment]
use ` --video-per-video` it will fix the problem

**Comment by imadyaici** [comment]
thank you @vahidm-sp this is how I could resume downloading this way, I had to download some courses from scratch before this
