### ISSUE TITLE
SSL Issue.. (windows 10)

### ISSUE THREAD

**Issue by digvijay442** [li-xinyang/OS_FrontendMaster-dl#74]
Not able to download the course.........facing SSL certificate issue...............

[0316/150902.789:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
[0316/150902.794:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0316/150904.749:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics

Login with your credential
Downloading course: javascript-hard-parts
[0316/150932.653:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://embedwistia-a.akamaihd.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://frontendmasters.com/courses/javascript-hard-parts/ (0)
Retrieving: javascript-hard-parts/JavaScript_The_Hard_Parts/Introduction
Video URL: http://placehold.it/500x500
Retrieving: javascript-hard-parts/Principles_of_JavaScript/Global_Execution_Context
[0316/150957.634:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0316/150957.636:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics

**Comment by digvijay442** [comment]
[0319/105302.417:ERROR:gpu_process_transport_factory.cc(1009)] Lost UI shared context.
[0319/105302.419:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0319/105302.419:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics

DevTools listening on ws://127.0.0.1:12673/devtools/browser/f0ee8643-f054-4e66-a4ae-d3c1fbead141
[0319/105303.025:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0319/105303.025:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
>>> Login with your credential
>>> Downloading course: js-fundamentals-functional-v2
Retrieving: js-fundamentals-functional-v2/JavaScript_From_Fundamentals_to_Functional_JS/Course_Introduction
[0319/105322.683:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://embedwistia-a.akamaihd.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://frontendmasters.com/courses/js-fundamentals-functional-v2/ (0)
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "C:\webdrivers\OS_FrontendMaster-dl-master\extractor\spider.py", line 52, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "C:\webdrivers\OS_FrontendMaster-dl-master\extractor\spider.py", line 178, in _get_downloadable_links
    resolution_button.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: headless chrome=64.0.3282.186)
  (Driver info: chromedriver=2.37.543627 (63642262d9fb93fb4ab52398be4286d844092a5e),platform=Windows NT 10.0.16299 x86_64)


C:\webdrivers\OS_FrontendMaster-dl-master>[0319/105334.817:ERROR:instance.cc(49)] Unable to locate service manifest for metrics
[0319/105334.819:ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
