### ISSUE TITLE
urllib2.URLError: <urlopen error unknown url type: blob>

### ISSUE THREAD

**Issue by oliviaoddo** [li-xinyang/OS_FrontendMaster-dl#75]
It seemed to be working but crashed at the end. `
urllib2.URLError: <urlopen error unknown url type: blob>`
```
Video URL: blob:https://frontendmasters.com/4b2ed450-d4d1-44a0-93f2-ebf3f40a54d7
Retrieving: web-security/HTTPS_Downgrade/Certificate_Authority_Compromise
Video URL: blob:https://frontendmasters.com/fb4e8ca9-5e81-49c5-a17d-77b9e577c528
Retrieving: web-security/Wrapping_Up/Wrapping_Up_Web_Security
Video URL: blob:https://frontendmasters.com/7528de11-f7d3-4543-befa-ab7ecc738b62
Downloading: Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/oliviaoddo/Sites/Enki/OS_FrontendMaster-dl/extractor/spider.py", line 56, in download
    self.download_course(course_downloadbale)
  File "/Users/oliviaoddo/Sites/Enki/OS_FrontendMaster-dl/extractor/spider.py", line 219, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/Users/oliviaoddo/Sites/Enki/OS_FrontendMaster-dl/extractor/spider.py", line 230, in download_video
    download_file(subsection['downloadable_url'], file_path)
  File "/Users/oliviaoddo/Sites/Enki/OS_FrontendMaster-dl/extractor/helper.py", line 52, in download_file
    buff = urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: blob>
```

**Comment by timolinn** [comment]
I have this same issue. Any help please?

**Comment by mitrikyle** [comment]
I spent an hour debugging this and finally realized it was all because my password was incorrect. Make sure your password is correct and it should work.

**Comment by gixid192** [comment]
I'm having the same error today, could you help me check please?
As I'm using the latest version, I don't think my password is incorrect.
