### ISSUE TITLE
Stopped while getting the video URLs

### ISSUE THREAD

**Issue by mohitgarg** [li-xinyang/OS_FrontendMaster-dl#77]
This is the error logged

```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/mohit/Documents/OS_FrontendMaster-dl/extractor/spider.py", line 55, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/mohit/Documents/OS_FrontendMaster-dl/extractor/spider.py", line 180, in _get_downloadable_links
    resolution_button = self.browser.find_element_by_class_name("fm-vjs-quality")
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 474, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 832, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"fm-vjs-quality"}
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by li-xinyang** [comment]
my guess is the target element could not be found on the page,

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"fm-vjs-quality"}
```

yeah, the button with classname `fm-vjs-quality`.

**Comment by gersongams** [comment]
I have the same error :cry:

**Comment by mugli** [comment]
Having the same error in some videos.

**Comment by vrymel** [comment]
This exception is probably the same:

```selenium.common.exceptions.ElementNotVisibleException: Message: element not visible```

**Comment by wu-yun** [comment]
this happens to me from time to time, however, when restart, the same video can be downloaded again.
