### ISSUE TITLE
Getting Error ..not able to  download any course

### ISSUE THREAD

**Issue by atishaybaid** [li-xinyang/OS_FrontendMaster-dl#78]
Following is the error.....we get after initiating the download command 

`Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.login(id, password)
  File "/Users/atishaybaid/OS_FrontendMaster-dl/extractor/spider.py", line 43, in login
    username_field.send_keys(id)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.13.2 x86_64)
`

**Comment by tucq88** [comment]
Same here :(

**Comment by DivuMarcus** [comment]
Same Here :-1:

**Comment by LocDaiNguyen** [comment]
same

**Comment by itsJagrati** [comment]
Same here! :(

**Comment by vvscode** [comment]
Has anyone tried https://github.com/li-xinyang/OS_FrontendMaster-dl/issues/70#issuecomment-379306690 ?

**Comment by nikhilmufc7** [comment]
I was getting the same error
I reinstalled chromedriver using homebrew this time and then recloned and it worked perfectly.

**Comment by LocDaiNguyen** [comment]
@nikhilmufc7 this worked for me

brew install chromedriver

I also had to do

brew link chromedriver

**Comment by tucq88** [comment]
Hmm, still not worked with me, I tried to reinstall requirements but facing this issue

```
  Could not find a version that satisfies the requirement setuptools>=18.5 (from html5lib>=0.999999999->mechanize->-r requirements.txt (line 2)) (from versions: )
No matching distribution found for setuptools>=18.5 (from html5lib>=0.999999999->mechanize->-r requirements.txt (line 2))
```
