### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sxhyxnchxng** [li-xinyang/OS_FrontendMaster-dl#80]
It had been working well but I got these errors and can't download any course.
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/sxhx/Documents/OS_FrontendMaster-dl/extractor/spider.py", line 52, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "/Users/sxhx/Documents/OS_FrontendMaster-dl/extractor/spider.py", line 82, in _get_detailed_course_list
    sections = self._get_section_data(sections_items)
  File "/Users/sxhx/Documents/OS_FrontendMaster-dl/extractor/spider.py", line 100, in _get_section_data
    course_section['title'] = titles[index].getText()
IndexError: list index out of range
```

**Comment by mxmlbernard** [comment]
Same here.

**Comment by joshpitzalis** [comment]
same here

**Comment by wu-yun** [comment]
https://github.com/li-xinyang/OS_FrontendMaster-dl/blob/master/extractor/spider.py#L91
try to change `h3 `to `h2 `here

**Comment by mxmlbernard** [comment]
It worked for me ! Thanks

**Comment by sxhyxnchxng** [comment]
Tried @wu-yun 's fix and It's working like a charm! Thanks

**Comment by li-xinyang** [comment]
PR merged, closing issue.
