### ISSUE TITLE
Message: 'chromedriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by testaccounthubgit** [li-xinyang/OS_FrontendMaster-dl#82]
Hello,

I'm getting this error:
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 12, in downloader
    spider = Spider(mute_audio)
  File "/home/philip/Desktop/PHILIP/OS_FrontendMaster-dl/extractor/spider.py", line 34, in __init__
    self.browser = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```
Where should I save the chromedriver?

Thanks.

**Comment by li-xinyang** [comment]
You can save the drive wherever you want and add that path to the environment path would make the script work ;)
