### ISSUE TITLE
ElementNotVisibleException

### ISSUE THREAD

**Issue by TheByteBits** [li-xinyang/OS_FrontendMaster-dl#83]
Today I've tried downloading a course and I got such message:

```
C:\Users\mzpk\Workspace\OS_FrontendMaster-dl (master)
λ git pull
Already up-to-date.

C:\Users\mzpk\Workspace\OS_FrontendMaster-dl (master)
λ python frontendmasters-dl.py --course computer-science --id <MyLogin> --password <MyPassword>  --mute-audio --high-resolution --video-per-video
[0425/115350.857:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12808/devtools/browser/5ce053f2-6bd0-4b45-b1c1-5e3f4383fa2a
>>> Login with your credential
>>> Downloading course: computer-science
[0425/115401.767:INFO:CONSOLE(0)] "The SSL certificate used to load resources from https://embedwistia-a.akamaihd.net will be distrusted in the future. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.", source: https://frontendmasters.com/courses/computer-science/ (0)
Retrieving: computer-science/Big_O__Recursion/Introduction
[0425/115406.342:INFO:CONSOLE(3)] "[event]", source: https://frontendmasters.com/next/assets/javascripts/player.js (3)
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "C:\Users\mzpk\Workspace\OS_FrontendMaster-dl\extractor\spider.py", line 55, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "C:\Users\mzpk\Workspace\OS_FrontendMaster-dl\extractor\spider.py", line 181, in _get_downloadable_links
    resolution_button.click()
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mzpk\AppData\Local\Continuum\anaconda2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: headless chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.3.9600 x86_64)
```
I'm seeing there are some reworks being done on frontendmasters.com, that may be a case. 
I'm running this on a Windows 8 machine with a non-admin account.

**Comment by jkomyno** [comment]
Same problem here

**Comment by vvscode** [comment]
@TheByteBits  @jkomyno  could you reproduce it with `web-development` course ? (I'm asking cause that course is free, and I could check without active subscription )

**Comment by jkomyno** [comment]
@vvscode Actually for me it worked after I removed the "--high-resolution" option. It was a free course btw
