### ISSUE TITLE
IndexError: list index out of range - when downloading any course

### ISSUE THREAD

**Issue by kempsterrrr** [li-xinyang/OS_FrontendMaster-dl#84]
Hi!

I am getting this error when trying to download any course. I've had this working in the past so I'm not sure what is causing the error now.

Please let me know if you need any other info

```
>>> Login with your credential
>>> Downloading course: functional-javascript-v2
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Users/Dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Dev/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/Dev/Desktop/development/tools/OS_FrontendMaster-dl/extractor/spider.py", line 49, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "/Users/Dev/Desktop/development/tools/OS_FrontendMaster-dl/extractor/spider.py", line 79, in _get_detailed_course_list
    sections = self._get_section_data(sections_items)  File "/Users/Dev/Desktop/development/tools/OS_FrontendMaster-dl/extractor/spider.py", line 97, in _get_section_data
    course_section['title'] = titles[index].getText()
IndexError: list index out of range
```

**Comment by stalwart201** [comment]
@kempsterrrr same issue here. By any chance is it resolved? or any clue.

**Comment by vvscode** [comment]
I have no active subscription, however I checked on `javascript-basics` ( it's free ) and it works

**Comment by vvscode** [comment]
@stalwart201  @kempsterrrr  could you update downloader and check it on `javascript-basics` ?

**Comment by msreekm** [comment]
I wish FEM had an option to download and view the courses offline in desktop! then the community does not need to hack  to view the courses offline!

**Comment by li-xinyang** [comment]
Their model is charging for subscription and I do not think there is any reason they would need to do so in the short run.

**Comment by vinhlh** [comment]
This is another approach you can try
https://github.com/vinhlh/frontendmasters-crawler
