### ISSUE TITLE
 Message: 'chromedriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by karocksjoelee** [li-xinyang/OS_FrontendMaster-dl#85]
gh-resolution
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "C:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 12, in downloader
    spider = Spider(mute_audio)
  File "E:\OS_FrontendMaster-dl-master\extractor\spider.py", line 34, in __init__
    self.browser = webdriver.Chrome(chrome_options=options)
  File "C:\python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\python27\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by karocksjoelee** [comment]
I solved by using chocolaty 

https://chocolatey.org/packages/chromedriver

**Comment by karocksjoelee** [comment]
But I still face some error 

`>>> Login with your credential
>>> Downloading course: sql-fundamentals
[0513/024919.623:WARNING:spdy_session.cc(2991)] Received HEADERS for invalid stream 3
[0513/024919.632:WARNING:spdy_session.cc(2991)] Received HEADERS for invalid stream 3
Retrieving: sql-fundamentals/Foundations_of_Relational_Databases/Welcome__Tech_Check
[0513/024925.734:INFO:CONSOLE(3)] "[event]", source: https://frontendmasters.com/next/assets/javascripts/player.js (3)
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "C:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "E:\OS_FrontendMaster-dl-master\extractor\spider.py", line 55, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "E:\OS_FrontendMaster-dl-master\extractor\spider.py", line 181, in _get_downloadable_links
    resolution_button.click()
  File "C:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "C:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: headless chrome=66.0.3359.139)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)`

**Comment by karocksjoelee** [comment]
I've fixed by remove the --mute-audio  --high-resolution
Thank you very much !! but I am facing that 

429: You have reached maximum request limit. Sleeping for 15 minutes

But, it doesn't just sleep for 15 minutes

**Comment by li-xinyang** [comment]
Glad to hear that; A PR to fix that issue is welcomed. Cheers.
