### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by webcrazy** [li-xinyang/OS_FrontendMaster-dl#86]
Sorry I'm not familiar with python. so. here's the log. 
```
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Users/wmw/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wmw/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/wmw/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wmw/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/wmw/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 49, in download
    course_detailed_list = self._get_detailed_course_list(course)
  File "/Users/wmw/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 79, in _get_detailed_course_list
    sections = self._get_section_data(sections_items)
  File "/Users/wmw/Downloads/OS_FrontendMaster-dl/extractor/spider.py", line 97, in _get_section_data
    course_section['title'] = titles[index].getText()
IndexError: list index out of range
```

**Comment by webcrazy** [comment]
sorry duplicate issue
