### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by jizusun** [li-xinyang/OS_FrontendMaster-dl#87]
Hi!

I am getting this error when trying to log in. I've had this working in the past so I'm not sure what is causing the error now.

Please let me know if you need any other information.

Thanks!

```
$  python frontendmasters-dl.py --id my_id --password my_password --course testing-react
[14532:9420:0520/102249.327:ERROR:gpu_process_transport_factory.cc(1007)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:12491/devtools/browser/d20f3492-14b6-46f0-9e2d-56ff83e436c3
>>> Login with your credential
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.login(id, password)
  File "C:\Users\I337932\Downloads\_Lynda\OS_FrontendMaster-dl\extractor\spider.py", line 43, in login
    username_field.send_keys(id)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.14393 x86_64)
```

**Comment by li-xinyang** [comment]
Seems you are using an outdated Webdriver version. Try to upgrade it first and see if the error persists.

https://github.com/webdriverio/webdriverio/issues/2631

**Comment by jizusun** [comment]
Thank, it works! :rocket::rocket::rocket:
I should have googled this log error message :smile:

Best regards,
Jizu
