### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'

### ISSUE THREAD

**Issue by geirman** [li-xinyang/OS_FrontendMaster-dl#88]
While running this command `python frontendmasters-dl.py --high-resolution --id my@email.com --password myP@ssW0rd --course advanced-graphql` (with correct credentials)

I'm getting this response...
```
>>> Login with your credential
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 14, in downloader
    spider.login(id, password)
  File "/Users/ChrisGeirman/dev/node/OS_FrontendMaster-dl/extractor/spider.py", line 43, in login
    username_field.send_keys(id)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=67.0.3396.79)
  (Driver info: chromedriver=2.34.522932 (4140ab217e1ca1bec0c4b4d1b148f3361eb3a03e),platform=Mac OS X 10.13.4 x86_64)
```

**Comment by dper0718** [comment]
Please send in the output of `chromedriver --version` in your terminal
