### ISSUE TITLE
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible

### ISSUE THREAD

**Issue by andrepadez** [li-xinyang/OS_FrontendMaster-dl#89]
```
>>> Login with your credential
>>> Downloading course: git-in-depth
Retrieving: git-in-depth/Git_In-Depth/Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/andrepadez/Downloads/frontendmasters-dl/extractor/spider.py", line 55, in download
    course_downloadbale = self._get_downloadable_links(course_detailed_list, high_resolution, video_per_video)
  File "/Users/andrepadez/Downloads/frontendmasters-dl/extractor/spider.py", line 181, in _get_downloadable_links
    resolution_button.click()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: headless chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.5 x86_64)
```

**Comment by andrepadez** [comment]
this happens when flag --high-resolution is on

**Comment by li-xinyang** [comment]
I believe your PR just fixed this issue. Thanks @andrepadez.

**Comment by andrepadez** [comment]
Really happy to help :)

**Comment by li-xinyang** [comment]
Thanks for the PR the current script is so troublesome and I'm thinking to start from scratch again by using APIs instead.

**Comment by andrepadez** [comment]
oh, i was actually thinking of doing a bit more work on it, just trying to find someone with python skills to help me out

**Comment by li-xinyang** [comment]
😅 i do not have a subscription and i do not have a planed date for it yet, and i plan to write the "new" script using JS instead.
