### ISSUE TITLE
Breaks on "Learn Advanced SVG Animation"

### ISSUE THREAD

**Issue by matthewepler** [li-xinyang/OS_FrontendMaster-dl#95]
Here's the tail of the output, where the error occurs:
```

Video URL: https://static.frontendmasters.com/assets/videos/promo/afxtleydqi/1080.webm
Retrieving: svg-animation/MorphSVG/Resources_and_Course_Wrap-Up
Video URL: https://static.frontendmasters.com/assets/videos/promo/afxtleydqi/1080.webm
Downloading: SVG_Introduction
Traceback (most recent call last):
  File "frontendmasters-dl.py", line 24, in <module>
    downloader()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "frontendmasters-dl.py", line 17, in downloader
    spider.download(course, high_resolution, video_per_video)
  File "/Users/matthewepler/Documents/tutorials/OS_FrontendMaster-dl/extractor/spider.py", line 59, in download
    self.download_course(course_downloadbale)
  File "/Users/matthewepler/Documents/tutorials/OS_FrontendMaster-dl/extractor/spider.py", line 224, in download_course
    self.download_video(i1, i2, subsection, section_title, course_path)
  File "/Users/matthewepler/Documents/tutorials/OS_FrontendMaster-dl/extractor/spider.py", line 232, in download_video
    i1, i2, subsection, section_title, course_path
  File "/Users/matthewepler/Documents/tutorials/OS_FrontendMaster-dl/extractor/helper.py", line 16, in get_local_file_path
    extension = get_file_path_from_url(subsection['downloadable_url'])
  File "/Users/matthewepler/Documents/tutorials/OS_FrontendMaster-dl/extractor/helper.py", line 43, in get_file_path_from_url
    return url.split("?")[0].split(".")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Mikhail-MM** [comment]
Can you write how you invoked the script?

**Comment by zhangrui19950516** [comment]
You should use the name in the url. Not the course name. Sometimes they are not equal.
